package Classes;

import java.io.Serializable;

public enum CategorieQuestionEnfant {
   STRUCTURE_FAMILIALE,
   DYNAMIQUE_FAMILIALE,
   ANTECEDANTS_FAMILIAUX,
   CONDITIONS_NATALES,
   DEVELOPPEMENT_PSYCHOMOTEUR,
   DEVELOPPEMENT_LANGAGIER,
   CARACTERE_COMPORTEMENT,
}